require "nokogiri"
require "open-uri"
require "bundler"
require "pry" 
require_relative "../lib/user_interface"
require_relative "../lib/concerns/memorable" 
require_relative "../lib/scraber.rb" 
require_relative "../lib/brand_name"